### ISSUE TITLE
Game gets stuck on a few chroma songs when playing online using MultiplayerExtensions on 1.29.1

### ISSUE THREAD

**Issue by GeorgeMixas** [Aeroluna/Heck#104]
**Describe the bug**
When playing moded online using beattogether AND MultiplayerExtensions (it doesn't happen without MultiplayerExtensions) the game will get stuck in "[waiting for other players](https://prnt.sc/iBqpDd8a4H6K)" right after clicking play in the multiplayer lobby.

This only happens in a few songs that use chroma, not all chroma songs, an example of a song that does this is 
https://beatsaver.com/maps/2cbb6

Since that song can be played without chroma lights as well, if I remove chroma the song plays without problems during online play.
**To Reproduce**
1. Get BS 1.29.1
2. Install chroma 2.7.16 and get the [following](https://prnt.sc/C_kTmOZqnsFn) mods to be able to play online plus MultiplayerExtensions. 
3. Get the song linked above.
4. Make a lobby and click play on the song 
5. [See error](https://prnt.sc/iBqpDd8a4H6K)

**Expected behavior**
For the song to play normally without getting stuck at the above screen.
**Additional context**
[latest.log](https://github.com/Aeroluna/Heck/files/14476181/latest.log)

**Comment by RedBrumbler** [comment]
Do you know whether everyone in the lobby has chroma? That might be important

**Comment by GeorgeMixas** [comment]
I know that this happens in an empty lobby where you are the only player, as long as MultiplayerExtensions and Chroma are installed as stated above.

I'm 99% sure that this also happens when any other number of players have Chroma installed since I have gotten this issue when playing with people who should have it installed but I'm not certain about it.

I don't know if this issue occurs when you have Chroma and MultiplayerExtensions installed but other people don't have Chroma, if that's the case then normally you shouldn't even be able to start Chroma songs since the multiplayer mod checks to see if everyone has Chroma before letting you start a song that needs it.

I would be willing to help as a second player with or without Chroma installed if it would help troubleshoot the issue.

**Comment by Aeroluna** [comment]
Appears to be a bug when using the "Solo Environment" option in MultiplayerExtensions on maps that duplicate a `LightPairRotationEventEffect`. This is likely a bug that needs to be fixed within MultiplayerExtensions and how it handles zenject resolving for environments.
As MultiplayerExtensions hasn't seen updates in a year nor been approved for newer game versions, this won't be worked on
