### ISSUE TITLE
All Chroma Geo in "newer Maps" will appear compleatly Black

### ISSUE THREAD

**Issue by DasMaloon** [Aeroluna/Heck#108]
**Describe the bug**
All Chroma Geo in "newer Maps" will appear compleatly Black (exept for specular highlights).
For some Reason this does not happen on some maps (like swifters acloudyskye pack as far as I can tell) but it does happen in 2023 Cube-Community-Rewind or other Elecast Maps like Paradigm or even a small remapper-Test i made once with just 2 simple Cubes.

(This issue porably isnt that important, its just that I am still stuck in 1.34.2, because other Mods i currently need, arent out yet for newer versions)

**To Reproduce**
1. Open Beatsaber 1.34.2 (_Heck 1.5.1, Chroma 2.8.1, Mapping Ext. 1.7.4)
2. Load into 2023 Cube-Community-Rewind, or any map with Chroma Geo (afaik its irrelevant wether its colored or not)

Here is an example of my dumb remapper-Test
![image](https://github.com/Aeroluna/Heck/assets/102411739/f0971a23-947a-4b42-b5cc-c0cacd946a27)
Cubes have theese Properties
scene.addPrimaryGroups(
        "Cube", // Material Name
        new rm.Geometry("Cube", { 
          shader: "Standard", 
          color: [100, 100, 100], //extreme Value for test purposes
        }),
    );

**Expected behavior**
Chroma geo should be displayed in its actual color, not just specular highlights

**Additional context**
[_latest.log](https://github.com/Aeroluna/Heck/files/15268555/_latest.log)

**Comment by Mawntee** [comment]
This has already been addressed and fixed: https://github.com/Aeroluna/Heck/pull/105
Not sure if it's been pushed out to GitHub or BeatMods yet, but Aero should have the fix out soon!
