### ISSUE TITLE
Chroma standard environments load on 360/90 maps

### ISSUE THREAD

**Issue by UrkiMimi** [Aeroluna/Heck#114]
**Describe the bug**
The title is mostly self explanatory. This bug happens if you use an environment that isn't GlassDesert with a 360/90 map.

**To Reproduce**
1. Use a Chroma environment that doesn't use GlassDesert as a base
2. Play a 360/90 map

**Expected behavior**
Chroma shouldn't load the environment if it's not meant for 360 maps

**Additional context**
Video showing the bug
https://github.com/user-attachments/assets/2711d9c0-f07e-4deb-855d-f234688ef9a3
Log: [_latest.log](https://github.com/user-attachments/files/16504439/_latest.log)

**Comment by MrCubicYT** [comment]
This seems intentional, if not keep it and call it a feature, I like playing 360 maps on non 360 environments...

**Comment by UrkiMimi** [comment]
I mean this could be but the game HUD doesn't rotate with the map which can become a problem with 360 maps.

**Comment by Aeroluna** [comment]
This is intentional
