### ISSUE TITLE
recommended settings not working properly

### ISSUE THREAD

**Issue by GnyawUwU** [Aeroluna/Heck#118]
**Describe the bug**
When I play a chroma map that requires mirror quality to 3 I accept the settings but the mirror quality remains 0

**To Reproduce**
1. Play a map that requires mirror quality to 3
2. click on accept 
3. the map starts but on mirror quality 0

**Expected behavior**
the map should start on mirror quality 3

**Additional context**
the bug happens on version 2.9.1 for 1.37.1, additional context: i have mirror quality off by default
[_latest.log](https://github.com/user-attachments/files/16930695/_latest.log)

**Comment by Mawntee** [comment]
Just out of curiosity and unrelated to the issue, but why does your map "require" the highest quality mirror setting to function?

**Comment by GnyawUwU** [comment]
Well the map is on a “sea alike” chroma environment, so the water reflection is an important part of the environment, especially because if I play it without mirror quality it looks like I’m standing on nothing

**Comment by GnyawUwU** [comment]
Sorry didn’t mean to close it!

**Comment by Aeroluna** [comment]
fixed https://github.com/Aeroluna/Heck/commit/ad476a8409faa03995a9c4e6ddcbbec633484da6
