### ISSUE TITLE
BS 1.37.1: Multiplayer not possible with Heck/Chroma installed

### ISSUE THREAD

**Issue by WorldofShadows** [Aeroluna/Heck#119]
**Describe the bug**
Beat Saber Version 1.37.1
Playing Multiplayer with BeatTogether is not possible with Chroma/Heck installed.
When loading a song the map stays black for some time until the game returns to the lobby. Saber haptic feedback can be felt when the Sabers are touching while everything is black.

When uninstalling _heck and/or Chroma, MP works fine again.

**To Reproduce**
1. Go to Multiplayer / Create Server (BeatTogether) / Let people join
2. Choose any song, Custom / Official doesn't matter
3. Start the Song
4. See error described above

**Expected behavior**
Multiplayer working fine with Heck and Chroma installed and Technicolor activated

**Additional context**
This is a completely fresh Beat Saber install on 1.37.1, installed over BSManager, no old remnants present.
The Mods are downloaded over BSManager and all required mods installed and double checked

Logfiles:
Logfile where the issue is happening:
[2024.09.17.18.47.42.log.gz](https://github.com/user-attachments/files/17033450/2024.09.17.18.47.42.log.gz)

Latest Logfile with uninstalled Chroma/Technicolor and working MP:
[_latest.log](https://github.com/user-attachments/files/17033566/_latest.log)

Edit: Totally forgot :) The issue is discussed at the BeatTogether Discord and the suggestion for now is to disable Heck and Chroma for now. I'd thought it's better to let you know about this.

**Comment by Aeroluna** [comment]
fixed https://github.com/Aeroluna/Heck/commit/be2fe1256b3aea82b6e5c5b3422ddb9f85334524
