### ISSUE TITLE
BeatSaber 1.37.1 - Using BSManager Chroma does not load songs when multiple people are playing

### ISSUE THREAD

**Issue by swimwater** [Aeroluna/Heck#123]
**Describe the bug**
I'm using BSManager and so is my friend. The version of the game is 1.37.1 and the most recent version of Chroma 2.9.1+1.37.1

When playing multiplayer, any map that has Chroma will go to the "Waiting for Players" screen, and then it will eventually time out and go back to the song selection screen.

If you try and play a chroma map alone in a multiplayer sever it loads just fine. It only occurs when playing with multiple people.

**To Reproduce**

1. Install Chroma and BeatTogether for Beat Saber 1.37.1
2. Open a multiplayer server
3. Have a friend join you
4. Select any song that uses chroma
5. Try and play the song
6. Get sent back to lobby

**Expected behavior**
1. Install Chroma and BeatTogether for Beat Saber 1.37.1
2. Open a multiplayer server
3. Have a friend join you
4. Select any song that uses chroma
5. Try and play the song
6. Song loads, and you get to play with your friends

**Additional context**
[_latest.log](https://github.com/user-attachments/files/17535955/_latest.log)

**Comment by Aeroluna** [comment]
duplicate https://github.com/Aeroluna/Heck/issues/119
