### ISSUE TITLE
Starting an OST map causes critical errors and a black screen.

### ISSUE THREAD

**Issue by CodeSoftGit** [Aeroluna/Heck#129]
**Describe the bug**
Starting an OST map causes critical errors and a black screen on 1.39.1 with the latest BeatMods version of every mod at time of posting.

**To Reproduce**
1. Have 1.39.1 and Chroma 2.9.10+1.39.0 installed
2. Select any OST map
3. Press play

**Expected behavior**
The map should have started and played as normal.

**Additional context**
[_latest.log](https://file.io/RBO25HTJ0mvL)

**Comment by Meivyn** [comment]
The log you posted has been deleted. You should edit your post and just drag and drop it into the edit box to upload it here.

**Comment by CodeSoftGit** [comment]
I have absolutely no idea what changed but this issue is no longer present
