### ISSUE TITLE
Stuff on the bottom of the mod chart is blacked out. 

### ISSUE THREAD

**Issue by Lyndenthebeast99** [Aeroluna/Heck#13]
![Beat Saber 12_8_2021 5_44_39 PM](https://user-images.githubusercontent.com/95829264/145304195-5fd644c3-413a-42ef-9521-9678e4d3e17a.png)

**Comment by UrkiMimi** [comment]
What version are you on?

**Comment by Aeroluna** [comment]
This comes from a change in Beat Saber v1.18.2 where notes and walls are now affected by the fog. This is a vanilla effect and won't be changed. Chroma v2.5.7 offers a [event that lets mappers adjust the fog](https://github.com/Aeroluna/Heck/wiki/Animation#AssignFogTrack) but mappers will need to implement this on their end.
