### ISSUE TITLE
[Bug][1.39.1] Failing in a specific map soft locks the game

### ISSUE THREAD

**Issue by ElaineGilstrom** [Aeroluna/Heck#132]
**Describe the bug**
In the map "Time to beat the odds" on the current version, if you fail (specifically without nofail on), the game soft locks. When you fail, the game looks similar to if you had nofail turned on, but the menu stops working and eventually the notes stop coming.

Deleting chroma resolves the bug, so that is what makes me think this is a chroma bug. I haven't tested this with a fresh install with nothing but chroma installed, so I'm not 100% certain it is just chroma though.

Link to map: https://beatsaver.com/maps/3f7f2

**To Reproduce**

1. Go to the song "Kagetora. - Time to beat the odds (extended)"
2. Click Play on any of the difficulties.
3. The choice with the heck settings screen doesn't change anything
4. Die
5. Get soft locked into the map

**Expected behavior**
Exiting out of the map after dying ;)

**Additional context**
From what I can tell, it looks like what is happening is some crucial object was deleted, then the game got stuck in a callback loop trying to access the deleted element. I am 100% not an expert on this so I could be very wrong though.

The first log file is the entire log from starting the game to causing the bug.
[_latest.log](https://github.com/user-attachments/files/18032847/_latest.log)

This second log file is narrowed down to just about the minute before I triggered the bug for the first time tonight. This particular log file kept on going repeating the last few lines over and over for probably 10000+ lines.
[log.txt](https://github.com/user-attachments/files/18032848/log.txt)

**Comment by Aeroluna** [comment]
Duplicate https://github.com/Aeroluna/Heck/issues/128
