### ISSUE TITLE
Map not working correctly in latest 1.39.1

### ISSUE THREAD

**Issue by Kiritosblade** [Aeroluna/Heck#134]
First off, i'm not 100% sure this is even a chroma related issue, i've no idea what is actually the issue but what little info i do have is pointing toward either chroma or maybe the map itself?

-Versions-
Game: 1.39.1
Chroma: 2.9.10.0

So my game seems completely fine with using any map at all, minus this one specific map which is using chroma, back in 1.29.1 this works flawlessly, as of now when trying it on 1.39.1 i'm only able to see the first 3 notes and some of the walls, rest of the map
 is empty, the actual json file (.dat) does indeed contain all the correct information etc, so not the issue (unless mapping versions are to blame, idk). 
I had someone test it as well to make sure this was not a me issue, it's not lol.
The map is "Deity Mode" on beatsaver, it's a scoresaber only ranked map (not ranked on BL), link is
<https://beatsaver.com/maps/34a3d>

My Log:
[_latest.log](https://github.com/user-attachments/files/18050685/_latest.log)

**Comment by TheBlackParrot** [comment]
Ran into this as well with this map, turning on static lights at least lets you play the map.

**Comment by Kiritosblade** [comment]
> Ran into this as well with this map, turning on static lights at least lets you play the map.

100% going to be doing that bc i really just wanted to play the map lmao.

**Comment by Kiritosblade** [comment]
if static lights being enabled 'fixes' the issue, does this maybe just mean that chroma has a method or something that shares names with something in the base game now and that's conflicting ofc so the actual attempt to move lights via the map data is resulting in the entire thing not even working as intended? Idk just a guess

**Comment by Kiritosblade** [comment]
Okay so uh. It does indeed 'work' this way. But it throws you into no fail mode, with no ability to pause the map to my knowledge. But i mean, it does allow you to play it when you bypass the recommended settings thing by hitting decline lol.

**Comment by Aeroluna** [comment]
Duplicate #128
