### ISSUE TITLE
CustomPlatforms Incompatibility 

### ISSUE THREAD

**Issue by UrkiMimi** [Aeroluna/Heck#14]
**Describe the bug**
CustomPlatforms TubeLights are not compatible with chroma no matter what map it is

**To Reproduce**
1. Install Custom Platforms
2. Use a Custom Platform with Tube Lights included
3. Play any song

**Expected behavior**
Tube Lights that are dynamic are going to disappear and will not be present in the entire map. However static tube lights are not affected by this nor static objects.

**Additional context**
Both of these images are shown with static lights turned on.

Top image shows whats supposed to happen

![image](https://user-images.githubusercontent.com/74517821/145927677-d8d11b7f-dc5f-4eb0-bf4e-bb75b479231e.png)

Bottom image shows the thing that happens when Chroma is installed

![image](https://user-images.githubusercontent.com/74517821/145927816-2f27ae4c-16c1-49d0-9b1e-97f17f1be4f3.png)

[_latest.log](https://github.com/Aeroluna/Heck/files/7708438/_latest.log)

**Comment by aggrogahu** [comment]
New Chroma version destroys the base game LightSwitchEventEffect and replaces it with a new Chroma-specific class apparently.

**Comment by Arrogantergamer** [comment]
is there gonna be any fix to it? because i really like to use custom platforms and technicolor

**Comment by aggrogahu** [comment]
> is there gonna be any fix to it? because i really like to use custom platforms and technicolor

I believe a fix is somewhere in these commits. https://github.com/Aeroluna/Heck/compare/128685b75244...2bc9dffd6815 So yes, it's being addressed.

**Comment by Aeroluna** [comment]
Fixed in https://github.com/Aeroluna/Heck/commit/48f366eb163a87ff678c11ae3c964d9b2c214c25
