### ISSUE TITLE
Seemingly random performance issues, possibly isolated to headset?

### ISSUE THREAD

**Issue by mxkris** [Aeroluna/Heck#15]
**Describe the bug**
Over the last few months, I have noticed some mod maps to be unplayable at times. I have spent hours trying to sort out software/hardware issue and have come up short on answers.

I've been able to reproduce this thru multiple versions of Heck/Noodle/Chroma and Beat Saber. I have tried to isolate what mods/settings have an effect on performance by adding one mod at a time and changing one settings at a time. I've done testing with and without OBS running, streaming or recording as well as closing as many background tasks as possible.

Either the maps play perfectly, or they are a slideshow. I can play the maps without issues one session and have them be completely unplayable in another. Maps with lots of wall spam and other effects seem to work fine; it almost feels like a very specific effect used in some of the problem maps I have encountered is grumpy about some mod or some setting and tanks the FPS.

Feedback from viewers and reviewing stream footage, the game output window is super smooth, but the performance in headset is completely off. During the songs that play the worst, when the issue is happening, the SteamVR performance chart goes completely yellow and peaks/valleys erratically.

**To Reproduce**
Play certain noodle maps that are heavier on effect usage, examples: ill by roughsketch (1ba93), illuminate by duumu (177e8), shelter by Porter Robinson (1ad55)

**Expected behavior**
Consistent performance between sessions.

**Additional context**
I am happy to provide any logs, footage or perform any kinds testing/profiling to help isolate/diagnose this issue but I am currently at a loss on what to try next.

**System specs:**
i7 8700k @4.8ghz
32gb DDR 3000
MSI RTX 3070ti
Valve Index

**Comment by Mawntee** [comment]
You mentioned OBS... Are you using LIV by chance? (MR, Avatars, Streamerkit, etc etc)

**Comment by mxkris** [comment]
I've been able to reproduce this issue with LIV running, or not, -and- with or without Camera2+NalulunaAvatars

I've tried a clean install > basic mods for just custom maps > test working > try LIV OR Camera2+NalulunaAvatars > test working > open OBS and test > tested working > try again the next day > some noodle/chroma songs are slideshows in the headset

I tried capturing video of this in action but the game output or LIV output run at full FPS but in the headset itself, the game is unplayable. I don't think I've tried capturing the HMD mirror in SteamVR, maybe I can try to get a side by side capture of what I am seeing in the headset versus what is being output in the client.

It's been super frustrating because it is very specifically certain maps that use specific bloom/distortion/lighting effects. Maps like Meiso Flip, ANALYS and The Wall all run fine.

Perhaps it's a settings in the vanilla client, or one of my mods, or a SteamVR setting, but I have tried everything I can think of over the weeks before breaking down to submit this issue.

FWIW, I've heard some anecdotal stories from a couple other players having similar issues with the same maps I have been using as examples, I just don't have anything concrete.

**Comment by mxkris** [comment]
> You mentioned OBS... Are you using LIV by chance? (MR, Avatars, Streamerkit, etc etc)

I've been able to reproduce this issue with LIV running, or not, -and- with or without Camera2+NalulunaAvatars

I've tried a clean install > basic mods for just custom maps > test working > try LIV OR Camera2+NalulunaAvatars > test working > open OBS and test > tested working > try again the next day > some noodle/chroma songs are slideshows in the headset

I tried capturing video of this in action but the game output or LIV output run at full FPS but in the headset itself, the game is unplayable. I don't think I've tried capturing the HMD mirror in SteamVR, maybe I can try to get a side by side capture of what I am seeing in the headset versus what is being output in the client.

It's been super frustrating because it is very specifically certain maps that use specific bloom/distortion/lighting effects. Maps like Meiso Flip, ANALYS and The Wall all run fine.

Perhaps it's a settings in the vanilla client, or one of my mods, or a SteamVR setting, but I have tried everything I can think of over the weeks before breaking down to submit this issue.

FWIW, I've heard some anecdotal stories from a couple other players having similar issues with the same maps I have been using as examples, I just don't have anything concrete.

**Comment by Toys0125** [comment]
So only thing I believe that could help would be to get a frame time graph output using SteamVR frame timing.
The docs do have a great expiation on what each part means and if you would like a .csv output file to further dig into is likely to help further. [https://developer.valvesoftware.com/wiki/SteamVR/Frame_Timing](https://developer.valvesoftware.com/wiki/SteamVR/Frame_Timing)

**Comment by Aeroluna** [comment]
Closed for inactivity
