### ISSUE TITLE
Player movement broken in multi

### ISSUE THREAD

**Issue by whymoo** [Aeroluna/Heck#18]
**Describe the bug**
I know multiplayer is not officially supported/not a focus of development but just so people know, I want to report that since noodle version 1.4.6 play movement is broken in multiplayer on noodle extension maps

**To Reproduce**
1. Join multiplayer lobby
2. Play any map with player movement like scary hour or dadadada
3. In part of map with any player movement the player stays in place

**Expected behavior**
The player moves like in singplayer

**Additional context**
This has happened to everyone I talked to in multiplayer so idk if log is necessary but here is the error that I believe is related to this issue

[CRITICAL @ 18:15:08 | UnityEngine] InvalidOperationException: Could not find PauseController.
[CRITICAL @ 18:15:08 | UnityEngine] NoodleExtensions.Animation.PlayerTrack.AssignTrack (Heck.Animation.Track track) (at <ca72ddf02e5e43d3b7d2b6db99d415f9>:0)
[CRITICAL @ 18:15:08 | UnityEngine] NoodleExtensions.Animation.Events.AssignPlayerToTrack.Callback (CustomJSONData.CustomBeatmap.CustomEventData customEventData) (at <ca72ddf02e5e43d3b7d2b6db99d415f9>:0)
[CRITICAL @ 18:15:08 | UnityEngine] CustomJSONData.CustomEventCallbackController.LateUpdate () (at <7bcec1873f4e494bbe4fc2e3ab58326d>:0)
[CRITICAL @ 18:15:08 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object.
[CRITICAL @ 18:15:08 | UnityEngine] (wrapper dynamic-method) IPA.Utilities.FieldAccessor`2[PauseController,System.Boolean].<>_accessor___paused(PauseController&)
[CRITICAL @ 18:15:08 | UnityEngine] NoodleExtensions.Animation.PlayerTrack.Update () (at <ca72ddf02e5e43d3b7d2b6db99d415f9>:0)
[CRITICAL @ 18:15:08 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object.

Full log: https://paste.c-net.org/TequilaScrolls

**Comment by whymoo** [comment]
Forgot to say this is on 1.18.3 with noodle 1.4.6, since multi isn't out yet for 1.19. Player movement works if you downgrade noodles and dependencies to noodle 1.4.4

**Comment by Aeroluna** [comment]
Will have to wait for Multiplayer Extensions to be released for current BS version to confirm
