### ISSUE TITLE
Feature request: ability to set type of duplicated lights, not just lightID

### ISSUE THREAD

**Issue by cumber** [Aeroluna/Heck#25]
I've been experimenting with using Chroma to "de-brand" some of the environments that came with artist-specific DLC packs, so that I could use them in custom maps.

Using `_environment` to disable the branding elements works great. Then I saw in the docs that we could use `_duplicate` and `_lightID`:

> If you are duplicating a light with id or something that contains a light with id, it will attempt to assign it to this light id.

I mistakenly thought that would allow me to duplicate some other elements and assign them to the lighting track used by the central logo, since I've removed that; it would give me a way of still using that "channel", and means if someone plays the map without Chroma it'll still work basically the same.

So I tried this:

````json
"_environment": [{
  "_id": "LeftLaser",
  "_lookupMethod": "Contains",
  "_duplicate": 1,
  "_position": [3, 3, 3],
  "_lightID": 0
}
````

But the new element is responding to the left laser track, not the main logo track. I saw in the logs:

```
[DEBUG @ 13:57:29 | Chroma] ID ["LeftLaser"] using method [Contains] found:
[DEBUG @ 13:57:29 | Chroma] SkrillexEnvironment.[0]Environment.[21]LeftLaser
[DEBUG @ 13:57:29 | Chroma] SkrillexEnvironment.[0]Environment.[21]LeftLaser.[0]BakedBloom
[DEBUG @ 13:57:29 | Chroma] SkrillexEnvironment.[0]Environment.[21]LeftLaser.[1]BoxLight
[DEBUG @ 13:57:29 | Chroma] Duplicating [SkrillexEnvironment.[0]Environment.[21]LeftLaser]:
[DEBUG @ 13:57:29 | Chroma] Registered key [0] to type [2].
```
Which made it clear that I can pick the individual light id, but it still inherits the track (type) from the original element, so not what I was after. Even if I use Chroma events to manually target that id, it's still part of type 2, so all the regular left laser events will *also* have to use Chroma events to manually target all light ids in type 2 *except* for my new ones.

I had a bit of a look at the code (though I'm not the most familiar with C# or Unity code), and it looks like it's possible for the type to be set from code. Would it be possible/reasonable to add a `_type` field to `_environment`, that overrides the type of duplicated lights as well?

**Comment by Aeroluna** [comment]
Added in https://github.com/Aeroluna/Heck/commit/8368e0adea80d730d2aee170d2acbc9ea3eb015b
