### ISSUE TITLE
Noodle Extensions angles change in 360 Degrees

### ISSUE THREAD

**Issue by iswimfly** [Aeroluna/Heck#26]
**Bug**

When creating Noodle Extensions effects in 360 Degree maps, if the map rotates any number of degrees using 360 events the definition of 0 (in regards to rotation) changes to match the rotation of the map. 

**To Reproduce**
1. Create a map with at least 1 360 rotation event
2. Place 2 walls - 1 before and 1 after the 360 event with the same rotation applied (using _definiteposition helps with visualizing the difference)

**Expected Behavior**
Walls should have the same rotation regardless of 360 rotation events.

**Comment by Aeroluna** [comment]
The code around this issue has been rewritten a lot since this was first opened, can you verify that it still happens with the latest MA release?

**Comment by iswimfly** [comment]
[I believe this is still an issue.](https://streamable.com/gmx97k)

Using `_definiteposition` with *base game* 360 rotation events still results in the rotation changing.

[Here's the difficulty as well.](https://github.com/Aeroluna/Heck/files/8526999/Expert360Degree.txt)

**Comment by Aeroluna** [comment]
I'm not understanding the issue, the map you sent has no rotations applied? If that's intentional, then it is intended for definitePosition to still respect 360 events.
![image](https://user-images.githubusercontent.com/40481393/164369919-ea081b17-c0ce-4ce2-a0b5-da4df65a81d5.png)

**Comment by iswimfly** [comment]
Is it intended for all Noodle properties including _rotation to respect 360 events? Because if so, this issue can be closed. 
[Here's a different difficulty.](https://github.com/Aeroluna/Heck/files/8527159/Expert360Degree.txt)
In that difficulty, the rotation remains 15 for each of the walls, yet the angle is well beyond 15 when 360 events are introduced.

**Comment by Aeroluna** [comment]
I was confusing the _rotation field and the _rotation animateable property.

Respecting 360 events is intended.
https://github.com/Aeroluna/Heck/wiki/AnimationProperties#_rotation
> This property describes the world rotation **offset** of an object.
