### ISSUE TITLE
Chroma/NoodleExtentions/Heck not on ModAssistant

### ISSUE THREAD

**Issue by Avera9eJoe** [Aeroluna/Heck#27]
Greetings! I'm unsure what the best method of contact is, but I do not see any of these mods in ModAssistant, despite reading this is the preferred method of installing them. Am I missing something?

**Comment by TzurS11** [comment]
restart your pc 10 times spin around your chain 5 times then jump 20 times and lastly run 5 miles naked OR just wait :/

**Comment by Avera9eJoe** [comment]
> restart your pc 10 times spin around your chain 5 times then jump 20 times and lastly run 5 miles naked OR just wait :/

Are they not in ModAssistant because they aren't updated? I apologize for my lack of understanding, I only installed Beat Saber yesterday.

**Comment by TzurS11** [comment]
just wait

**Comment by Avera9eJoe** [comment]
> just wait

What do I wait for?

**Comment by Supersonicboss1** [comment]
Noodle extensions, Chroma, and Heck are not yet updated for the latest version of Beat Saber, so they aren't available in ModAssistant yet. When they are ready, it will likely be added.

**Comment by TzurS11** [comment]
you can also check on [BeatMods](https://beatmods.com/#/mods)

**Comment by Avera9eJoe** [comment]
> Noodle extensions, Chroma, and Heck are not yet updated for the latest version of Beat Saber, so they aren't available in ModAssistant yet. When they are ready, it will likely be added.

Ah gotcha. Thank you for the straight reply!
