### ISSUE TITLE
Black screen when trying to launch maps that require NE/Chroma

### ISSUE THREAD

**Issue by RohdeOfficial** [Aeroluna/Heck#28]
**Describe the bug**
Whenever I try to go into any map that requires either Noodle Extensions and/or Chroma, the game just goes to a black screen, and nothing else happens

**To Reproduce**
1. Launch any map that requires Noodle Extensions and/or Chroma
2. See error

**Expected behavior**
I expected to be able to launch the maps that require these specific mods.

**Additional context**
I have reinstalled Heck, Noodle Extensions, Chroma, BSIPA, SiraUtil etc. multiple times, both with ModAssistant and manually, all to no avail.
[https://drive.google.com/file/d/1nU_6FmsSaUP-3_tSDvD_9Qc9a6ACmIGv/view?usp=sharing](url) Link to my BS log, as GitHub wouldn't let me upload the direct file

**Comment by Aeroluna** [comment]
The link you provided says "Files is in owner's trash."

**Comment by RohdeOfficial** [comment]
Sorry about that, link should hopefully be working now.

**Comment by Aeroluna** [comment]
Even after installing the same mods you have installed, I can't replicate the issue. Can you try installing just NE/Chroma and seeing the issue persists and also posting which maps are causing the issue?

**Comment by Aeroluna** [comment]
Looks like this is caused by modifiers/options that transform the BeatmapData, like left-handed mode.
