### ISSUE TITLE
Unable to play non-chroma maps with heck.dll loaded into Beat Saber

### ISSUE THREAD

**Issue by KayTacy** [Aeroluna/Heck#3]
I'm having an issue where if heck.dll is loaded to get chroma working standard non chroma/noodle maps aren't loading their stages and are unplayable but work fine if heck.dll is removed.

**Comment by starvide** [comment]
Heck just Doesnt Let you play Dont worry about it It might be fixed

**Comment by Fatalution** [comment]
> I'm having an issue where if heck.dll is loaded to get chroma working standard non chroma/noodle maps aren't loading their stages and are unplayable but work fine if heck.dll is removed.

Can't reproduce. Please provide the _latest log if that ever happens again to you

**Comment by Amunarch** [comment]
I am apparently not allowed to press play, and can't play any maps at all when heck.dll is there. But for me too it works if i remove heck.dll.

**Comment by Fatalution** [comment]
> I am apparently not allowed to press play, and can't play any maps at all when heck.dll is there. But for me too it works if i remove heck.dll. Like the maps load in i'm just not allowed to press play.

Please provide _latest.log found in the UserData/Logs

**Comment by starvide** [comment]
Here this might Help 
[WARNING @ 10:47:22 | [Plugins/IniParser.manifest] Failed to find info
[WARNING @ 10:47:22 | [Plugins/Heck.dll] Failed to find info

I found this In my logs Folder And Only put that

**Comment by Fatalution** [comment]
> Here this might Help 
> 
> [WARNING @ 10:47:22 | [Plugins/IniParser.manifest] Failed to find info
> 
> [WARNING @ 10:47:22 | [Plugins/Heck.dll] Failed to find info
> 
> 
> 
> I found this In my logs Folder And Only put that

This tells nothing - it's just the warning that comes up because those files are not posted on BeatMods.

The only thing that is helpful is the _latest.log found in UserData/Logs, after experiencing a behavior that you would think is a bug. 

ONLY that. Nothing else.

You won't find ANY help unless you provide this file

**Comment by gmiz92** [comment]
[latest.log](https://github.com/Aeroluna/Heck/files/6660235/latest.log)
This log should have the relevant information to this behavior

**Comment by Fatalution** [comment]
> [latest.log](https://github.com/Aeroluna/Heck/files/6660235/latest.log)
> 
> This log should have the relevant information to this behavior

1. I see you don't have Chroma installed
2. You Noodle Extensions are outdated

**Comment by Aeroluna** [comment]
Closed for inactivity from original poster
