### ISSUE TITLE
NoodleExtensions/Chroma Songs Stuck Loading, Black Screen

### ISSUE THREAD

**Issue by Wrcts** [Aeroluna/Heck#30]
This Bug has already been reported, but I wanted to give more detailed info on my interaction with it.
**Describe the bug**
When loading any song that uses Chroma/NoodleExtensions, instead of actually loading into the song, the game gets stuck loading, leaving you in a black void. I have uninstalled and reinstalled the game and my mods multiple times, I have checked the integrity of the game files with steam over 10 times now, and I have tried about every possible combination of mods possible, including the releases of the mods from yesterday, and the pre-releases from today.

**To Reproduce**
1. Load any song that uses Chroma/NoodleExtensions
2. See error

**Expected behavior**
A song that loads

**Additional context**
The Video has more mods loaded than when the log file was loaded, so;
Mods Loaded When The Provided Log File Was Generated: BSIPA, SongCore, NoodleExtensions, Heck, CustomJSONData, LookupID, SiraUtil, Ini Parser, BeatSabermarkupLanguage, BS Utils, Chroma

LOG FILE:
[_latest.log](https://github.com/Aeroluna/Heck/files/8406115/_latest.log)

https://user-images.githubusercontent.com/96028993/161460019-fa57b768-7b3f-42e4-8ace-4d5b72ee72bc.mp4

**Comment by Aeroluna** [comment]
Duplicate https://github.com/Aeroluna/Heck/issues/28
