### ISSUE TITLE
Custom song infinite loading

### ISSUE THREAD

**Issue by cloud454555** [Aeroluna/Heck#31]
ive downloaded noodle extensions off mod assistant im not sure why but everytime i download it im not able to play the custom songs i have but the basic ones work ive also uninstalled and the custom songs continue to work is there mods that are conflicting with it ?

**Comment by thojo0** [comment]
I have the same problem and I found out, the Problem is happening from CustomJSONData.
Here is what I found in the Player.log (what I think is the Problem):
```
FieldAccessException: Field `BeatmapSaveDataVersion3.BeatmapSaveData:version2_6_0' is inaccessible from method `CustomJSONData.CustomBeatmap.CustomBeatmapSaveData:Deserialize (string,System.Collections.Generic.Dictionary`2<string, object>,System.Collections.Generic.Dictionary`2<string, object>)'
```

**Comment by Aeroluna** [comment]
Please follow the template and make sure to upload your log from `Beat Saber/Logs/_latest.log` .

@thojo0 This is an issue from updating a modded Beat Saber from an older version, delete `Beat Saber\UserData\Beat Saber IPA.json` to fix your game.

**Comment by thojo0** [comment]
Ok thx
