### ISSUE TITLE
saber trail misaligned on noodle maps

### ISSUE THREAD

**Issue by wobbleorange** [Aeroluna/Heck#32]
**Describe the bug**
There is a misalignment between the saber and saber trail, only appearing with noodle maps.
Possible cause SaberTrailRenderer(Clone) - I'm not finding this item in rue on non-noodle maps.

**To Reproduce**
1. load any map with noodle extensions as a requirement
2. saver trail appears off to the side, almost 90 deg to main saber

**Expected behavior**
saber and trail should align

**Additional context**
[saber trail log.txt](https://github.com/Aeroluna/Heck/files/8413080/saber.trail.log.txt)
[saber trail _latest.log](https://github.com/Aeroluna/Heck/files/8413100/saber.trail._latest.log)

![sabertrail](https://user-images.githubusercontent.com/91919415/161629347-5246498f-f122-4f12-aecd-1c61af5671b9.png)
![sabertrail2](https://user-images.githubusercontent.com/91919415/161629360-7f865606-7b35-4439-86ba-35314160ee10.png)
.

**Comment by thojo0** [comment]
I have the same issue.
I found out, this happens if you have a Space-Rotation defined in the Settings.
![Settings](https://user-images.githubusercontent.com/53666000/161632931-9e8e4a75-d5c2-4b4b-a317-44d9ff513b53.jpg)

**Comment by BS-Lime** [comment]
Quick remark in case that's a different thing: Also happens with maps that move the player around.

Easiest example: Washing Machine https://beatsaver.com/maps/11b28
More serious example: As The World Caves In https://beatsaver.com/maps/210e3
