### ISSUE TITLE
Billie Environment not quite right.

### ISSUE THREAD

**Issue by NullCase** [Aeroluna/Heck#33]
**Describe the bug**
Billie environment not displaying correctly. Here's an example.

What the song did look like: https://www.youtube.com/watch?v=J10B_jyAqzY
Here's the song to see how it looks now: https://beatsaver.com/maps/2148c

**To Reproduce**
1. Go to ['...' ](https://beatsaver.com/maps/2148c)
2. DL and Play the map
3. Compare to example video.
4. notice that the visuals are off.

**Expected behavior**
Visuals as displayed in the example video.

**Additional context**
Yeah, it looks like the channels (or whatever they're called) are off so that the Billie environment no longer displays correctly.

**Comment by oadugmore** [comment]
I'm having the same issue. [Here's the log](https://github.com/Aeroluna/Heck/files/8458031/_latest.log) from a play session where I started the game, played this level, and exited.

**Comment by XAce1337manX** [comment]
Adding more info to this.

**Current behaviour:**
The left sunbeams (`"_type" : 2`) and the right water lasers `("_type" : 11)` are always on and are always the orange colour in the default Billie colour palette.

I suspect these issues would be related to the current bugs present in base game on Billie environment for version 1.21.0. The mappings for the rain in base game is not functioning as intended (being tied to the wrong light type) so something in this would likely affect Chroma mappings.

**Comment by Vadezz** [comment]
Just gonna add two of my maps that also have this problem, maybe it helps with fixing it i dont know.

https://beatsaver.com/maps/1f7d2
https://beatsaver.com/maps/220e2

**Comment by Vadezz** [comment]
I also just noticed that "Water 2" and "Water 3" seem to trigger the sun beams and lasers.
![image](https://user-images.githubusercontent.com/103857652/165559842-2eac1e0b-33ce-45a0-a1ef-1e86eb21a3c6.png)
 Same beat in the song  
![image](https://user-images.githubusercontent.com/103857652/165559689-7edc29b1-4b52-4992-ad77-8bdffbb05ad0.png)
