### ISSUE TITLE
Improper wall placements and scale in 1.21

### ISSUE THREAD

**Issue by BrendonGames** [Aeroluna/Heck#38]
Whilest playing a noodle map on 1.21 walls are not properly placed/scaled. At first while playing walls act just fine, but after a while walls just do whatever they want. (proper example in video's)

**To Reproduce**
Play a few maps (idk if they **_have_** to be noodle)
Play a map that requires noodle (preferably one with a lot of walls)
You'll see that all/most walls aren't scaled and placed right

**Expected behavior**
The walls are supposed to be other sizes and in other places. (See [Signager](https://beatsaver.com/maps/12498) & [Ill by Sands](https://beatsaver.com/maps/1ba93) for what they are supposed to look like)

**Additional context**
Log:
[_latest.log](https://github.com/Aeroluna/Heck/files/8583251/_latest.log)

Video's:
 [Signager](https://youtu.be/HgAXfYyR59I)
 [Ill by Sands](https://youtu.be/_oleASmU3Ik)

(My pc is just barely able to run Beat Saber and I got a lot of lag in the headset, so ignore my gameplay XD)

**Comment by Aeroluna** [comment]
Seeing as the original issue has Mapping Extensions installed and the first step is "Play a few maps (idk if they have to be noodle)", I will assume this particular case is the Mapping Extensions bug.

@Mawntee Please create separate issues for each issue and provide more information such as how things are "improperly scaled" or which events "don't occur".

As for "Also if static lights are switched off by settings setter, then it also go brokey", see https://github.com/Aeroluna/Heck/issues/34
