### ISSUE TITLE
The walls get thicker in the Y-axis direction

### ISSUE THREAD

**Issue by hato9690** [Aeroluna/Heck#41]
**Describe the bug**
#29 seemed to be resolved with the modification of Mapping extensions 1.7.2.
But some Maps that use both Noodle extensions and Mapping extensions still seem to have problems.

**To Reproduce**
for example :
https://beatsaver.com/maps/e4a3
https://beatsaver.com/maps/23a70

bsr 23a70:
OK (beatsaber v1.16, Mapping extensions 1.5.2)
![correct](https://user-images.githubusercontent.com/104088542/166875161-7e1286ec-b57b-4954-a63f-5508a0197b9f.png)

NG(beatsaber v1.21, Mapping extensions 1.7.2)
![bad](https://user-images.githubusercontent.com/104088542/166875345-423530a1-7df4-4742-8a7e-c649de766d7c.png)

**Comment by Aeroluna** [comment]
From the README:
> MAPPERS: EITHER USE MAPPING EXTENSIONS OR NOODLE EXTENSIONS, DO NOT USE BOTH AT THE SAME TIME. Noodle Extensions is meant to completely replace Mapping Extensions, as they both do the same thing. Having both requirements can break some features.

Noodle Extensions implements all the features of Mapping Extensions and will conflict, compatibility will not be worked on.
