### ISSUE TITLE
NoodleExtention Saber Problem 

### ISSUE THREAD

**Issue by SM00NK** [Aeroluna/Heck#44]
**Describe the bug**
It is a bug with the saber where if I play a song in NoodleExtentions an extra line will just appear floating next to my saber

**To Reproduce**
1. Go to a song that has NoodleExtentions 
2. Click on The song and start it
3. Look at your sabers

**Expected behavior**
I expected to start a NoodleExtention map and my sabers to look normal

**Additional context**
Add any other context about the problem here. PLEASE ATTACH YOUR LOG FILE (Beat Saber\Logs\_latest.log) OR YOUR ISSUE MAY NOT BE LOOKED AT.

[_latest.log](https://github.com/Aeroluna/Heck/files/8646256/_latest.log)
^the log file

![saber problem](https://user-images.githubusercontent.com/105137586/167279686-5ba824a6-4963-46c3-9e49-b32358000d85.PNG)
^picture of the problem i'm having 

Just made an account so I don't know if I made this report right.
Sorry if I did something wrong :)

**Comment by Aeroluna** [comment]
Duplicate https://github.com/Aeroluna/Heck/issues/32. Fix awaiting beatmods approval
