### ISSUE TITLE
Map Light Effects not working as intended on certain map(s) past 1.19.1

### ISSUE THREAD

**Issue by roughavoc** [Aeroluna/Heck#45]
**Describe the bug**
RGB Lights for Map effects doesn't work on specific maps

**To Reproduce**
To see Intended behaviour
1. Load Beat Saber 1.19.1 
2. Download Song with code 12ad1
3. Skip to 1min, the circle map effects should change colour

To see broken behaviour:
1. Load Beat Saber 1.22 (I think this was an issue on 1.21 but I can't remember)
2. Repeat above
3. the circle map effects remain black 

[_latest.log](https://github.com/Aeroluna/Heck/files/8647647/_latest.log)
.

**Comment by Aeroluna** [comment]
Duplicate https://github.com/Aeroluna/Heck/issues/33
