### ISSUE TITLE
Dot Notes with Precision Placement changed to Down notes.

### ISSUE THREAD

**Issue by SyncBS** [Aeroluna/Heck#47]
**Describe the bug**
In maps with precision placed dots those have been changed to down notes. Two instances that I have noticed were https://beatsaver.com/maps/1e4c8 and https://beatsaver.com/maps/22300. 
![20220517040251_2](https://user-images.githubusercontent.com/86927709/168823187-a9775423-0995-4a40-9aa1-c01fd9c83411.jpg)
![image](https://user-images.githubusercontent.com/86927709/168823197-071c0d99-3913-4a7f-ac7b-14fd0cdbdedf.png)

**To Reproduce**
Check maps ingame vs beatsaver viewer or any mapping editor.

**Expected behavior**
Dots to be dots?

**Comment by Aeroluna** [comment]
Fixed <https://github.com/Aeroluna/Heck/commit/09d5c2086b03f140598e47dbc93c757cfe5c2587>
