### ISSUE TITLE
Chroma breaks with Beatmap V3 charts

### ISSUE THREAD

**Issue by the-Astra** [Aeroluna/Heck#48]
**Describe the bug**
Chroma seems to break and not read Chroma events in a Beatmap V3 chart

**To Reproduce**
Play any chart that uses both Beatmap V3 and Chroma (the specific chart that I've been troubleshooting with is this one: https://beatsaver.com/maps/2581d) 

**Expected behavior**
Chroma events are not properly represented in game; Lightshow plays like Chroma is not installed

**Additional context**
I have checked with a few other sources, and they are having the same issue as I am on the same chart. I also double checked the chart in Chromapper and the lights work as intended there. Adding on, this worked perfectly fine before update 1.22.1. I attempted downgrading to 1.22 but the issue persisted.

Log: [_latest.log](https://github.com/Aeroluna/Heck/files/8748708/_latest.log)

**Comment by Fernthedev** [comment]
While I haven't checked the beatmap json, (yet) are you aware that Chroma on v3 beatmap uses new keys and functionality in the customData format? Some few things were removed such as propId and gradients while the vast majority are renamed fields which can even have different functionality. 

I'll try to remember to check the beatmap later and see if the issue is indeed a genuine bug.

**Comment by the-Astra** [comment]
No, I wasn't aware of that. Now that I know this, I'm assuming the events used in the beatmap are using the older customData format from a Chromapper build that didn't support the new format that's in Chroma 2.5.13

**Comment by the-Astra** [comment]
I just updated my build and it works in Chromapper but not in game, so the issue is still unsolved

**Comment by Fatalution** [comment]
> I just updated my build and it works in Chromapper but not in game, so the issue is still unsolved

Yes, but ChroMapper uses older keys. It essentially displays what it shouldn't if the map is in v3 format. 

The whole Chroma syntax is changed for v3 maps. Those changes are not yet implemented in CM so it treats old syntax as it was for v2

**Comment by the-Astra** [comment]
> is

In that case, I wasn’t aware Chromapper’s latest v3 branch doesn’t have v3 lighting syntax implemented yet (at least that’s what I’m hearing from you). If that’s the root of the problem (which it seems to be) I’ll close the issue

**Comment by Aeroluna** [comment]
This is something that needs to be done in Chromapper
