### ISSUE TITLE
Loading a chroma map freezes the game

### ISSUE THREAD

**Issue by NagrandHero** [Aeroluna/Heck#58]
**Describe the bug**
The game freezes and goes to a black screen while loading any chroma map

**To Reproduce**
Play Chroma based map on 1.24

**Expected behavior**
The map should run

**LOG FILE**
[_latest.log](https://github.com/Aeroluna/Heck/files/9117278/_latest.log)

**Comment by Aeroluna** [comment]
Fixed https://github.com/Aeroluna/Heck/commit/2c0d08239982f68d8dd55421f6f0327124fcd6ce
