### ISSUE TITLE
What exactly _is_ "Heck"?

### ISSUE THREAD

**Issue by Whimb** [Aeroluna/Heck#6]
It'd be helpful if a module that gets marked as required had some kind of information that might explain what it is, or why it's been marked as required, without having to head to one of the Beat Saber Discords. :)

**Comment by thelightdesigner** [comment]
It handles tracks for Noodle/Chroma or any other future mods.

**Comment by Whimb** [comment]
Thanks for the clarification!
Could something to that effect perhaps be added to the repo/Mod Assistant, for convenience/clarity? 😄
