### ISSUE TITLE
Left-Handed Mode Causes Notes to "Lurch" in from the Left Side.

### ISSUE THREAD

**Issue by VeganFire** [Aeroluna/Heck#64]
Playing a map that requires NoodleExtensions with left-handed mode on causes notes to generate to the far left and then lurch into the normal track when they are closer.

**To Reproduce**
1. Play (most) songs requiring Noodle.
2. Wait a bit because it might take a bit to appear, depending on the song.
4. See bug.

**Expected behavior**
The map to be normal, not have notes appearing on the far left.

**Comment by queengooborg** [comment]
Hey @Aeroluna -- just curious, is there any ETA when a new version with the fix will be released?  This bug unfortunately makes some levels unplayable, and I would love to play them without practicing with my non-dominant (right) hand leading the way!

**Comment by Aeroluna** [comment]
@queengooborg I've just uploaded a fix to beatmods, will have to wait for approval
