### ISSUE TITLE
Heck Integration feature in Maps bugged

### ISSUE THREAD

**Issue by SyncBS** [Aeroluna/Heck#67]
https://www.twitch.tv/videos/1564786732

When a map has Heck Integration that uses counters+ / graphic settings it will enable those settings first and not start the map. After that your settings will stay active for other maps that don't use heck integration. Video explains and shows the issues.

**Comment by Mawntee** [comment]
Are you able to recreate the issue and attach a log file?

**Comment by SyncBS** [comment]
This issue happens every time a map with Game Settings is involved, no exceptions

[_latest.log](https://github.com/Aeroluna/Heck/files/9366358/_latest.log)

**Comment by Aeroluna** [comment]
Can't seem to get it to happen on my end, I can only assume its either because you are on an older version (1.23) or more likely a mod conflict is preventing the map from starting the first time. Please try removing a few mods at a time and see if it fixes the issue

**Comment by SyncBS** [comment]
This can be closed now as it's been fixed in later versions of the mod
