### ISSUE TITLE
Text not showing & object glitch

### ISSUE THREAD

**Issue by Lilobast** [Aeroluna/Heck#68]
Planes border doesn't connect very well and some text parts don't appear on recent versions

![image](https://user-images.githubusercontent.com/70602917/185762638-0b2567c7-a893-4e7c-aad6-96472b09c4b0.png)

**To Reproduce**
Play Beat Saber 1.21 or above
Download this level: https://beatsaver.com/maps/1a839
and just play

**Expected behavior**
It should look like this:
![image](https://user-images.githubusercontent.com/70602917/185762666-0f14c31f-695a-430b-8655-5d5cf84a0265.png)

**Additional context**
Heck 1.4.2
NoodleExtensions 1.5.2
Chroma 2.6.2
Logs:
[_latest.log](https://github.com/Aeroluna/Heck/files/9387892/_latest.log)

**Comment by Aeroluna** [comment]
Seems to be caused by the change in jump duration calculations in BS 1.20
