### ISSUE TITLE
In NoodleExtensions 1.5.2, the landing of a left-right crossed note jump is shifted to the side.

### ISSUE THREAD

**Issue by rynan4818** [Aeroluna/Heck#69]
**Describe the bug**
When using version 1.5.2 on a MAP with NoodleExtensions, the jump landing points are shifted sideways in areas where the placement of the notes is reversed left to right.

**To Reproduce**

Check out the video below for a comparison of the MAPs played.

https://beatsaver.com/maps/28608

Game version 1.24.0
CustomJSONData: 2.4.1
Heck: 1.4.3
LookupID: 1.0.1
Chroma: 2.6.2
NoodleExtensions: 1.5.2

![2](https://user-images.githubusercontent.com/14249877/188316924-0e148169-a95f-4a90-b6ee-0dd59fb332e9.gif)

----

Game version 1.24.0
CustomJSONData: 2.4.1
Heck: 1.4.1
LookupID: 1.0.1
Chroma: 2.6.1
NoodleExtensions: 1.5.1

![3](https://user-images.githubusercontent.com/14249877/188316929-15b80e03-bff3-4e4d-a206-c643ec84f82c.gif)

**Comment by Mawntee** [comment]
This has been reported before and is known, but dang ty for taking the time to make a gif with a red square and everything to report the bug! It's much appreciated. 

This bug is annoying me too, so I'll continue to cyber bully Aero until it's fixed :)

**Comment by rynan4818** [comment]
I see that this problem has already been reported.
I hope this will be fixed as I play a lot of maps with Noodle these days.

**Comment by Aeroluna** [comment]
Fixed in https://github.com/Aeroluna/Heck/commit/d9c62def9016b14a8f0929928d88ece6d4cd8f69
