### ISSUE TITLE
source is null

### ISSUE THREAD

**Issue by Gamer1120** [Aeroluna/Heck#72]
**Describe the bug**
Install bunch of mods on Beat Saber 1.24.0. Open game, click Play on song, nothing happens. Keep spamming play, nothing happens. Same for custom songs.

[2022.10.29.11.24.56.log](https://github.com/Aeroluna/Heck/files/9893351/2022.10.29.11.24.56.log)

**Comment by Aeroluna** [comment]
The version of heck you have installed (Heck v1.4.5) is built for Beat Saber 1.25.0 and won't work for older versions. Either upgrade your game or grab an older version of Heck
