### ISSUE TITLE
[Enhancement] User Shared Environment Override Custom Platforms

### ISSUE THREAD

**Issue by SyncBS** [Aeroluna/Heck#76]
Would be quite good if we were able to keep the User Shared Environment turned on while deactivating the Custom Environment set by a mapper. 

Example:
If you have a User Shared Environment and the Map has a Custom Environment in itself, your User Shared Environment will not be used and instead will always use the Custom Environment from the Map. If you want to just use your User Shared Environment it's not possible. 

Video of what currently happens:
https://streamable.com/z3di8w
*if the map has custom environment in itself, your Custom Environment wont be shown and you'd need to disable custom environments all together and wont be able to use the user shared environment.

If a button to always use User Shared Environments were to be implemented then a player wouldn't need to disable the custom environments all together to not be using the Custom Environment on the Maps.

**Comment by Fatalution** [comment]
Considering that this change, if implemented in the current form, will completely destroy Chroma lights in any map that uses any other env - this should _only_ apply if the lights are set to static (No Effects).

**Comment by Mawntee** [comment]
iirc you can just select "Disable Environment Enhancements" and that will do the thing. 
Chroma environments are only forced if there are things in the environment that have been modified/removed. 

To me this bug actually looks like the opposite. 
imho it should be forcing the Chroma env regardless of if you have a custom environment selected. 

Although on second thought, Fatalutions idea is actually great as well. 
If you have Static Lights enabled it should not be switching to Chroma envs, and should use whatever is set by the user, not the mapper.

**Comment by Aeroluna** [comment]
The behavior with the "Disable Environment Enhancements" option that Mawntee describes is intended but it is not working correctly. It should be disabling the map's environment and using the user's.
