### ISSUE TITLE
feature request - stop overriding user set palettes

### ISSUE THREAD

**Issue by Dakota5488** [Aeroluna/Heck#80]
i have deuteranomaly, meaning my eyes are less sensitive to green light, this is fine in most maps as they respect my own colour palette override. a lot of maps using NE or Chroma however dont. This to me is a huge accessibility oversight, take the green day maps for example, to most of you it looks fine but to me the notes look exactly the same colour, so i have to take blind guesses and look very hard at slight differences in tone, im sure you can imagine this is not an easy task and makes playing those maps with the original palette really difficult. my request then is to have the option for NE maps to respect my own colour palette and not force one on the player that might be difficult to see, i love NE and beat saber, but yeah this is a small problem

**Comment by Mawntee** [comment]
Hello hi!

My name is Mawntee, I am also colour blind and yelled about this years ago!
There is an option in Chroma to disable note colouring just for this reason!
![image](https://user-images.githubusercontent.com/51247415/220236553-a630d142-9b4b-40a2-880d-b604453d363e.png)


There is also an option within SongCore as well to disable map specific colours and use the users preset custom colours.
Just click the little "question mark" icon on the song menu screen > Custom Colours Available > and uncheck the box.

![image](https://user-images.githubusercontent.com/51247415/220236890-56ff4727-69f1-49e9-b671-1eb0baf1304a.png)
![image](https://user-images.githubusercontent.com/51247415/220236909-d1093739-2145-41b9-9047-b3bb0bbed1f7.png)
![image](https://user-images.githubusercontent.com/51247415/220236916-37b8bf10-003d-48d5-982a-3d7683e31e94.png)

**Comment by Mawntee** [comment]
Added note for the first image:
If you don't see the "chroma tab" double check you haven't disabled or hidden it.
Click the "eye" icon on the right to show which mods may have been hidden.
