### ISSUE TITLE
Noodle Extension & LIV bug.

### ISSUE THREAD

**Issue by Kiritosblade** [Aeroluna/Heck#81]
```
This might not specifically be a NE problem, might be nothing you could do about it depending.
Basically when using Camera2 as first person camera, and LIV as third person,
When looking at footage after the fact (only knew to check because people pointed this out to me)
I'm unable to see certain custom assets in a NE map on the LIV camera but they are perfectly 
visible over on the first person Camera2 Cam.
```

```
1. Setup a third person camera using LIV from steam store, capture this in OBS or similar software.
2. Setup Camera2 plugin for first person view as full screen output in beat saber, 
then capture this as well in OBS/etc
3. Start recording
4. Play a custom map that uses NE like https://beatsaver.com/maps/d1cc this one. 
    ***Sorry, but only example I have***
5. When viewing after the fact you will notice that the 'custom assets' do not appear 
in the LIV camera but they do appear in Camera2 First person.
```

```
Expect the LIV camera to be able to see these custom assets.
```

```
Don't see a point in attaching log in this case as it's not something related to the actual issue
```

```
Again, sorry for nsfw content but this is the only example I have to provide
```
![example image](https://user-images.githubusercontent.com/9027884/221485085-68f8b2a1-3d0e-4059-b246-136087fdf3e4.png)

**Comment by Kiritosblade** [comment]
Picture provided was from after the fact just to show what i'm talking about.

**Comment by Mawntee** [comment]
hahaha the dickmaster strikes again!

Anyway, onto your issue...

LIV will "auto-invisible" walls. 
If you look at cam2 you will see that the walls are filled in red, where as in LIV the walls are completely see through, showing only the border. 

When using LIV and playing a Chroma/Noodle map, you will have to use the mod "invisible walls" (available in ModAssistant) and check the box "show in LIV" to make the third person LIV actually show the walls as they are intended. 

I'm closing this as it's not an issue with Chroma or Noodle, but just a weird "feature" of the LIV camera system.

**Comment by Kiritosblade** [comment]
Thank you! omg
