### ISSUE TITLE
Environment lookup ID's changing have broken old Chroma environments. 

### ISSUE THREAD

**Issue by Rain-Jur** [Aeroluna/Heck#82]
a lot of older maps such as lesbian ponies with weapons broke because of something. Mawntee told me to submit a report to heck but I don't know if the problem stems from here.
Here is a video of the map working completely normal: https://www.youtube.com/watch?v=tNtDm3odhLk
Map Link:
https://beatsaver.com/maps/17335
Apparently it's because beat games updated and the id's of objects changed, but all of these early noodle maps are broken and are now unplayable

**Comment by Mawntee** [comment]
Here is a screenshot from the _latest.log after playing the map. 
![image](https://user-images.githubusercontent.com/51247415/227086113-fabd4ec3-f14a-4e5d-b934-6d814b7a164d.png)
And a video clip from latest alpha release of the game: https://streamable.com/2bslx0

Not sure how ideal it is to re-assign or re-order all these objects, or maybe there's some other work around? 
I'm 99% sure this is mapper error though.

**Comment by Aeroluna** [comment]
There is not an easy way to keep ids the same across versions of the game
