### ISSUE TITLE
basicBeatmapEvents not being turned on

### ISSUE THREAD

**Issue by SyncBS** [Aeroluna/Heck#83]
**Describe the bug**
When using a User Shared Environment with Static Lights on Latest Mod Assistant Release for 1.28.beatgamesmoment the basicBeatmapEvents that we can add will not be initialized when map starts. This was fixed in a prior version that was not released but only for normal maps and that version is now broken in 1.28. 

**To Reproduce**
1. Create a User Shared Environment with some basicBeatmapEvents and use Static Lights;
2. Play Any Map;
3. 
![image](https://user-images.githubusercontent.com/86927709/227238281-6b86f057-423b-492e-8344-cfe11637047f.png)

**Expected behavior**
Light go weee, like this
![image](https://user-images.githubusercontent.com/86927709/227238169-cd44ce47-5ca8-4959-a60f-89385b415491.png)

**Additional context**
Logs in attached; Entered a Normal Map, Chroma Map, and Chroma Enhanced Environment Map.
[2023.03.23.14.40.14.log](https://github.com/Aeroluna/Heck/files/11052192/2023.03.23.14.40.14.log)

**Comment by Aeroluna** [comment]
Fixed https://github.com/Aeroluna/Heck/commit/655a90e2a7e3260e98a988525b20899990077058
