### ISSUE TITLE
Incompatible with multiplayer

### ISSUE THREAD

**Issue by queengooborg** [Aeroluna/Heck#92]
(I don't know whether to qualify this as a bug with MultiplayerCore or Noodle Extensions, but since the failing method is from Noodle Extensions, I opening it here would be most reasonable!)

When attempting to play a custom song that requires or recommends Noodle Extensions, the game fades to black and remains black for about ~10 seconds, before returning to the multiplayer lobby.  This occurs in both v1.29.1 with official mod versions downloaded via the Mod Assistant, and in v1.31.1 with versions compiled from source using the appropriate branches.

To reproduce:
1. Install `MultiplayerCore`, `BeatTogether`, `Noodle Extensions` and all required mods
2. Launch Beat Saber
3. Create a multiplayer server on a BeatTogether server (official or custom)
4. Play a map that requires/recommends Noodle Extensions

Attached is the log file showing the crash.  The "stripped" version only contains the relevant section of logs, but just in case, the full log has also been attached.
[_latest-stripped.log](https://github.com/Aeroluna/Heck/files/12705837/_latest-stripped.log)
[_latest.log](https://github.com/Aeroluna/Heck/files/12705838/_latest.log)

**Comment by GeorgeMixas** [comment]
I also have this issue.

**Comment by ewwfr** [comment]
How do i use playertransforms?

**Comment by Aeroluna** [comment]
That commit is a fix that is currently on the dev branch and will be released when the next version is uploaded.

**Comment by sleepy343** [comment]
This issue still happens with me and my friend on heck versions 1.6.3 and 1.6.0
