### ISSUE TITLE
Non-up to date versions for 1.29.1 prevents certain map effects.

### ISSUE THREAD

**Issue by Xentha** [Aeroluna/Heck#96]
Current versions available on Mod Assistant for 1.29.1 for Heck, Chroma and Noodle being out of date, has a significant effect on light shows and certain modmaps.

Primary loss in function is that Transition light events are parsed as basic On events at the end of their transition path, completely negating their intended function.
Secondary and more nebulous; A modmap by the name of Storyteller has multiple parts of its show either not function, or vanish outright. I do not know any specifics beyond that.

This of course doesn't prevent playing the given maps, but it both detracts from visual enjoyment, and of course, any light shows using transition events won't function properly.

**Comment by Aeroluna** [comment]
I've uploaded new versions for 1.29.1 (NE v1.5.16 and Chroma v2.7.16)
You'll have to wait for approval now

**Comment by Xentha** [comment]
Oh! Right-o. ^^ Sorry if this has already been in the works for a while.
I only noticed yesterday the version difference and figured I'd detail what effects it's been having.
Thank you for the prompt response!
I don't know the etiquette on Github Issue closing so I'll leave it at your discretion.
