### ISSUE TITLE
PlayerToTrack "target" break the game

### ISSUE THREAD

**Issue by Saltyfwish** [Aeroluna/Heck#97]
Using Target for player movement breaks: note mods, player movement, charting, and UI (softlocks the game by not being able to click on anything after leaving song) here's what it looks like 
https://github.com/Aeroluna/Heck/assets/41402537/aa9be1df-a232-4dba-a142-d3082a9fcc70

It seems to work fine in FPFC mode (sometimes) and so here's what it looks like in FPFC mode / what's meant to happen 
https://github.com/Aeroluna/Heck/assets/41402537/ac7e05af-0768-4f2d-9dbc-9db7ae897e7e

and here are my logs :)
[_latest.log](https://github.com/Aeroluna/Heck/files/13655970/_latest.log)

**Comment by Mawntee** [comment]
Are you able to share the map file as well?

**Comment by Saltyfwish** [comment]
Here's the file with the script too
[Unwelcome School.zip](https://github.com/Aeroluna/Heck/files/13665920/Unwelcome.School.zip)

I'm using the index with Steam/BSManager 1.29.1

**Comment by Mawntee** [comment]
Dawg, why do you have like 50 kabillion animate track events, all focusing the same player head/hand tracks, all with different durations and position offsets, but also all on the exact same beat??

That is clearly going to cause some issues.
![image](https://github.com/Aeroluna/Heck/assets/51247415/042f8922-b43b-46b4-b6ab-7d68d7223f91)

**Comment by Saltyfwish** [comment]
alright well I'll fix that issue and I'll see if it fixes it, I know why that's happening and also how to fix it. _shouldn't_ take that long
